-- MySQL Script generated by MySQL Workbench
-- mié 01 may 2019 13:10:14 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema builder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `priv_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `priv_capability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_capability` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` CHAR(250) NOT NULL,
  `description` TEXT NULL,
  `category_id` BIGINT NOT NULL DEFAULT 1 COMMENT 'ref to closure_caterory.id',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `category_id` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `priv_role_has_capability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_role_has_capability` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL,
  `capability_id` BIGINT NOT NULL,
  INDEX `cap_id` (`capability_id` ASC),
  INDEX `role_id` (`role_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique` (`role_id` ASC, `capability_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `priv_user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `priv_user_has_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id` (`role_id` ASC),
  UNIQUE INDEX `unique` (`user_id` ASC, `role_id` ASC),
  INDEX `user_id` (`user_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `priv_role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `priv_role` (`id`, `name`, `description`) VALUES (1, 'super admin', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `priv_user_has_role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `priv_user_has_role` (`id`, `user_id`, `role_id`) VALUES (1, 1, 1);

COMMIT;

